# Generated by Django 4.2.3 on 2024-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portrait/', verbose_name='Портрет')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Опыт')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('constitution', models.IntegerField(blank=True, null=True, verbose_name='Телосложение')),
            ],
            options={
                'verbose_name': 'Покемон',
                'verbose_name_plural': 'Покемоны',
                'ordering': ['id'],
            },
        ),
    ]
