# Generated by Django 4.2.3 on 2024-03-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0001_initial'),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='first_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Покемон', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='arena',
            name='second_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Противник', to='pokemon.pokemon'),
        ),
    ]
